
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author student
 */
public class ImageDisplayer extends javax.swing.JPanel {

    public void setImage(BufferedImage image) {
        imageLabel1.setImage(image);
    }

    public BufferedImage getImage() {
        return imageLabel1.getImage();
    }
    /**
     * Creates new form ImageDisplayer
     */
    public ImageDisplayer() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imageLabel1 = new ImageLabel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout imageLabel1Layout = new javax.swing.GroupLayout(imageLabel1);
        imageLabel1.setLayout(imageLabel1Layout);
        imageLabel1Layout.setHorizontalGroup(
            imageLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        imageLabel1Layout.setVerticalGroup(
            imageLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imageLabel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) throws Exception {
        ImageDisplayer displayer = new ImageDisplayer();
        BufferedImage image = ImageIO.read(new File("ClearWaterBay.jpg"));
        displayer.setImage(image);

        JFrame frame = new JFrame();
        frame.getContentPane().add(displayer);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(300, 200);
        frame.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ImageLabel imageLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
